import Head from "next/head";
import { Awards } from "../features/Awards";
import { FloatingActionButtons } from "../features/floating-action-buttons/FloatingActionButtons";
import { FullPage } from "../features/fullpage/FullPage";
import { Profile } from "../features/profile/Profile";
import { Projects } from "../features/projects/Projects";
import { ScrollDownIndicator } from "../features/scroll-down-indicator/ScrollDownIndicator";
import { TechSkills } from "../features/tech-skills/TechSkills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative">
          <div className="absolute inset-0 bg-fixed bg-gradient-to-br from-green-400 via-cyan-500 to-blue-500  dark:opacity-0 transition-opacity duration-500"></div>
          <div className="absolute inset-0 bg-fixed bg-gradient-to-br  from-pink-800 via-purple-800 to-indigo-800 opacity-0 dark:opacity-100 transition-opacity duration-500"></div>
          <FullPage
            sections={[
              <FullPage.Section key="0" title="Main" className="relative">
                <Profile />
                <div className="absolute bottom-5">
                  <ScrollDownIndicator />
                </div>
              </FullPage.Section>,
              <FullPage.Section key="1" title="Tech Skills">
                <TechSkills />
              </FullPage.Section>,
              <FullPage.Section key="2" title="Projects">
                <Projects />
              </FullPage.Section>,
              <FullPage.Section key="3" title="Awards">
                <Awards />
              </FullPage.Section>,
            ]}
          />
          <FloatingActionButtons />
        </div>
      </main>
    </>
  );
}
