import { Viewport } from "next";
import MainSectionContainer from "../features/main-section-container/MainSectionContainer";
import { ToggleDarkmodeButton } from "../features/toggle-darkmode-button/ToggleDarkmodeButton";

export const metadata = {
  title: "Curriculum Vitae",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default async function MainPage() {
  return (
    <>
      <MainSectionContainer />
      <div className="fixed bottom-8 right-8 flex flex-col gap-3 rounded-full">
        <ToggleDarkmodeButton />
      </div>
    </>
  );
}
